//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PrkCategotyOrders> PrkCategotyOrders { get; set; }
        public DbSet<PrkManufacturers> PrkManufacturers { get; set; }
        public DbSet<PrkOrderDetails> PrkOrderDetails { get; set; }
        public DbSet<PrkOrders> PrkOrders { get; set; }
        public DbSet<PrkOrderStatuses> PrkOrderStatuses { get; set; }
        public DbSet<PrkPickUpPoints> PrkPickUpPoints { get; set; }
        public DbSet<PrkRoles> PrkRoles { get; set; }
        public DbSet<PrkSuppliers> PrkSuppliers { get; set; }
        public DbSet<PrkUsers> PrkUsers { get; set; }
        public DbSet<PrkUunitOfMeasurements> PrkUunitOfMeasurements { get; set; }
        public DbSet<PrlProducts> PrlProducts { get; set; }
    }
}
