//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrkOrders
    {
        public PrkOrders()
        {
            this.PrkOrderDetails = new HashSet<PrkOrderDetails>();
        }
    
        public int IdOrder { get; set; }
        public int IdPickUpPoint { get; set; }
        public int IdUser { get; set; }
        public int IdOrderStatus { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public string CodeOrder { get; set; }
    
        public virtual ICollection<PrkOrderDetails> PrkOrderDetails { get; set; }
        public virtual PrkOrderStatuses PrkOrderStatuses { get; set; }
        public virtual PrkPickUpPoints PrkPickUpPoints { get; set; }
        public virtual PrkUsers PrkUsers { get; set; }
    }
}
