//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrkOrderDetails
    {
        public int IdOrderDetail { get; set; }
        public int IdProduct { get; set; }
        public int Quantity { get; set; }
        public int IdOrder { get; set; }
    
        public virtual PrkOrders PrkOrders { get; set; }
        public virtual PrlProducts PrlProducts { get; set; }
    }
}
