//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrkOrderStatuses
    {
        public PrkOrderStatuses()
        {
            this.PrkOrders = new HashSet<PrkOrders>();
        }
    
        public int IdOrderStatus { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual ICollection<PrkOrders> PrkOrders { get; set; }
    }
}
