//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrkPickUpPoints
    {
        public PrkPickUpPoints()
        {
            this.PrkOrders = new HashSet<PrkOrders>();
        }
    
        public int IdPickUpPoint { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Home { get; set; }
    
        public virtual ICollection<PrkOrders> PrkOrders { get; set; }
    }
}
