//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrkRoles
    {
        public PrkRoles()
        {
            this.PrkUsers = new HashSet<PrkUsers>();
        }
    
        public int IdRole { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<PrkUsers> PrkUsers { get; set; }
    }
}
