//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrkSuppliers
    {
        public PrkSuppliers()
        {
            this.PrlProducts = new HashSet<PrlProducts>();
        }
    
        public int IdSupplier { get; set; }
        public string Supplier { get; set; }
    
        public virtual ICollection<PrlProducts> PrlProducts { get; set; }
    }
}
