//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrkUsers
    {
        public PrkUsers()
        {
            this.PrkOrders = new HashSet<PrkOrders>();
        }
    
        public int IdUser { get; set; }
        public int IdRole { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<PrkOrders> PrkOrders { get; set; }
        public virtual PrkRoles PrkRoles { get; set; }
    }
}
