//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrlProducts
    {
        public PrlProducts()
        {
            this.PrkOrderDetails = new HashSet<PrkOrderDetails>();
        }
    
        public int IdProduct { get; set; }
        public int IdUnitOfMeasurements { get; set; }
        public int IdSupplier { get; set; }
        public int IdManufacturer { get; set; }
        public int IdCategotyOrder { get; set; }
        public string Article { get; set; }
        public string NameOrder { get; set; }
        public int Price { get; set; }
        public int Discount { get; set; }
        public string QuantityInStock { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual PrkCategotyOrders PrkCategotyOrders { get; set; }
        public virtual PrkManufacturers PrkManufacturers { get; set; }
        public virtual ICollection<PrkOrderDetails> PrkOrderDetails { get; set; }
        public virtual PrkSuppliers PrkSuppliers { get; set; }
        public virtual PrkUunitOfMeasurements PrkUunitOfMeasurements { get; set; }
    }
}
